local H = dofile("tests/helpers.lua")

describe("Sim", function()
	local Sim
	before_each(function() Sim = H.load().Sim end)

	local function run(sim, seconds)
		for _ = 1, math.floor(seconds * 60) do sim:update(Sim.STEP) end
	end

	it("replays the same course for the same seed", function()
		local a, b = Sim.new(42), Sim.new(42)
		run(a, 30); run(b, 30)
		assert.equal(a.d, b.d)
		assert.equal(#a.obstacles, #b.obstacles)
		for i, o in ipairs(a.obstacles) do
			assert.equal(o.a, b.obstacles[i].a)
			assert.equal(o.lane, b.obstacles[i].lane)
		end
	end)

	it("different seeds give different courses", function()
		local a, b = Sim.new(1), Sim.new(2)
		run(a, 10); run(b, 10)
		local same = #a.obstacles == #b.obstacles
		if same then
			for i, o in ipairs(a.obstacles) do
				if o.a ~= b.obstacles[i].a then same = false end
			end
		end
		assert.is_false(same)
	end)

	it("the bot never crashes", function()
		for seed = 1, 25 do
			local sim = Sim.new(seed * 7919)
			run(sim, 240)
			assert.equal(0, sim.crashes, "seed " .. seed .. " crashed")
		end
	end)

	it("the bot never crashes at max speed from the start", function()
		for seed = 1, 10 do
			local sim = Sim.new(seed, { speed0 = 26 })
			run(sim, 120)
			assert.equal(0, sim.crashes, "seed " .. seed .. " crashed")
		end
	end)

	it("actually generates obstacles of both kinds and jumps some", function()
		local sim = Sim.new(99)
		local kinds, jumped = {}, false
		for _ = 1, 60 * 120 do
			sim:update(Sim.STEP)
			for _, o in ipairs(sim.obstacles) do kinds[o.kind] = true end
			if sim.airT then jumped = true end
		end
		assert.is_true(kinds.train)
		assert.is_true(kinds.barrier)
		assert.is_true(jumped)
	end)

	it("changes lanes over time", function()
		local sim = Sim.new(5)
		local lanes = {}
		for _ = 1, 60 * 120 do
			sim:update(Sim.STEP)
			lanes[sim.target] = true
		end
		assert.is_true(lanes[-1] and lanes[0] and lanes[1])
	end)

	it("collects coins", function()
		local sim = Sim.new(3)
		run(sim, 60)
		assert.is_true(sim.coins > 20)
	end)

	it("keeps at least one lane free of trains at every point", function()
		local sim = Sim.new(1234)
		run(sim, 90)
		-- Collect every train ever generated by sampling as we go.
		local seen = {}
		local sim2 = Sim.new(1234)
		for _ = 1, 90 * 60 do
			sim2:update(Sim.STEP)
			for _, o in ipairs(sim2.obstacles) do seen[o.id] = o end
		end
		for x = 0, math.floor(sim2.d), 0.5 do
			local blocked = {}
			for _, o in pairs(seen) do
				if o.kind == "train" and o.a <= x and o.b >= x then blocked[o.lane] = true end
			end
			assert.is_false(blocked[-1] and blocked[0] and blocked[1] or false, "all lanes blocked at x=" .. x)
		end
	end)

	it("culls what is behind the runner", function()
		local sim = Sim.new(8)
		run(sim, 300)
		assert.is_true(#sim.obstacles < 60, "obstacles grew to " .. #sim.obstacles)
		assert.is_true(#sim.coinList < 200, "coins grew to " .. #sim.coinList)
		for _, o in ipairs(sim.obstacles) do assert.is_true(o.b >= sim.d - sim.cfg.behind) end
	end)

	it("ramps speed up to the cap", function()
		local sim = Sim.new(1)
		assert.equal(sim.cfg.speed0, sim.speed)
		run(sim, 200)
		assert.equal(sim.cfg.speedMax, sim.speed)
	end)

	it("drops time after a long hitch instead of spiralling", function()
		local sim = Sim.new(1)
		sim:update(10)
		assert.equal(0, sim.acc)
		assert.is_true(sim.t <= Sim.MAX_STEPS * Sim.STEP + 1e-9)
	end)
end)
